apply plugin: 'com.android.library'

android {
    namespace 'com.oissela.software.multilevelexpindlistview'
    compileSdkVersion 27

    defaultConfig {
        minSdkVersion 11
        targetSdkVersion 21
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    implementation 'androidx.appcompat:appcompat:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
}
